#!/bin/bash +x

TRUE=0
FALSE=1

# First ensure execution permissions for this script and directory.
# This is just to alert me to the RWX permissions.
stat .
stat $(basename ${0})

function exit_zero() {
    echo "Command exited with non-zero code ${?}." && exit 0
}

echo "Checking for existing changes."
git stash show && echo "WARNING. YOU ALREADY HAVE STASHED CHANGES."
git stash || exit_zero

git pull --all || exit_zero

echo "Unstashing the most recent stash."
git stash pop

echo
echo
echo "Most recent commits were"
git log --oneline -n 3 || exit_zero

echo
echo
echo "Grand total LOC"
wc -l $(find n* -name '*.py' -o -name '*.sql' -o -name '*.json' -o -name '*.md')
